# Generated by Django 4.2.3 on 2023-10-30 00:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_id', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('birth_no', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=13)),
                ('mothers_name', models.CharField(blank=True, max_length=254, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=254, null=True)),
                ('date_of_registration', models.DateTimeField()),
                ('date_of_birth', models.DateTimeField()),
                ('birth_facility', models.CharField(blank=True, max_length=254, null=True)),
                ('birth_county', models.CharField(choices=[('NAIROBI COUNTY', 'NAIROBI COUNTY'), ('KISUMU COUNTY', 'KISUMU COUNTY'), ('NYANDARUA COUNTY', 'NYANDARUA COUNTY'), ('NAKURU COUNTY', 'NAKURU COUNTY'), ('KERICHO COUNTY', 'KERICHO COUNTY'), ('BARINGO COUNTY', 'BARINGO COUNTY'), ('LAIKIPIA COUNTY', 'LAIKIPIA COUNTY'), ('MAKUENI COUNTY', 'MAKUENI COUNTY'), ('BOMET COUNTY', 'BOMET COUNTY'), ('BUSIA COUNTY', 'BUSIA COUNTY'), ('EMBU COUNTY', 'EMBU COUNTY'), ('ISIOLO COUNTY', 'ISIOLO COUNTY'), ('NANDI COUNTY', 'NANDI COUNTY'), ('NAROK COUNTY', 'NAROK COUNTY'), ('NYERI COUNTY', 'NYERI COUNTY'), ('KAKAMEGA COUNTY', 'KAKAMEGA COUNTY'), ('KERICHO COUNTY', 'KERICHO COUNTY'), ('BARINGO COUNTY', 'BARINGO COUNTY')], max_length=254)),
                ('resident_county', models.CharField(blank=True, choices=[('NAIROBI COUNTY', 'NAIROBI COUNTY'), ('KISUMU COUNTY', 'KISUMU COUNTY'), ('NYANDARUA COUNTY', 'NYANDARUA COUNTY'), ('NAKURU COUNTY', 'NAKURU COUNTY'), ('KERICHO COUNTY', 'KERICHO COUNTY'), ('BARINGO COUNTY', 'BARINGO COUNTY'), ('LAIKIPIA COUNTY', 'LAIKIPIA COUNTY'), ('MAKUENI COUNTY', 'MAKUENI COUNTY'), ('BOMET COUNTY', 'BOMET COUNTY'), ('BUSIA COUNTY', 'BUSIA COUNTY'), ('EMBU COUNTY', 'EMBU COUNTY'), ('ISIOLO COUNTY', 'ISIOLO COUNTY'), ('NANDI COUNTY', 'NANDI COUNTY'), ('NAROK COUNTY', 'NAROK COUNTY'), ('NYERI COUNTY', 'NYERI COUNTY'), ('KAKAMEGA COUNTY', 'KAKAMEGA COUNTY'), ('KERICHO COUNTY', 'KERICHO COUNTY'), ('BARINGO COUNTY', 'BARINGO COUNTY')], max_length=50, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_picture', models.ImageField(blank=True, default='images/default-avatar.jpg', null=True, upload_to='profile_pictures/children/%Y/%m/%d')),
                ('is_defaulter', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.doctor')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.parent')),
            ],
            options={
                'verbose_name_plural': 'Children',
                'db_table': 'child',
            },
        ),
        migrations.CreateModel(
            name='Vaccines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_id', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
                ('time_given', models.CharField(blank=True, max_length=254, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('duration_given', models.DurationField(blank=True, default=None, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='vaccines/%Y/%m/%d')),
                ('days_to_vaccine', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Vaccine',
                'verbose_name_plural': 'Vaccines',
                'db_table': 'vaccines',
            },
        ),
        migrations.CreateModel(
            name='ChildImmunization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_immunization_id', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('comment', models.TextField(blank=True, max_length=254, null=True)),
                ('immunization_date', models.DateTimeField(blank=True, null=True)),
                ('date_given', models.DateTimeField(blank=True, null=True)),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.child')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.doctor')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vaccines')),
            ],
            options={
                'verbose_name': 'Child Immunization',
                'verbose_name_plural': 'Child Immunizations',
                'db_table': 'child_immunization',
            },
        ),
    ]
